language: node_js
node_js:
- 'lts/*'
sudo: false
dist: trusty
before_install:
- wget -O arduino.tgz https://downloads.arduino.cc/arduino-1.8.1-linux64.tar.xz
- tar -xf arduino.tgz
- arduino-1.8.1/arduino --install-library "Adafruit Unified Sensor":1.0.2
- arduino-1.8.1/arduino --install-library "DHT sensor library":1.3.0
- cp secrets.example.h ./secrets.h
script:
- MICROFLO_TARGET=arduino npm run generate
- ARDUINO=`pwd`/arduino-1.8.1 npm run build
- make
- npm test
